version: '3.3'

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - DATABASE_PORT=6500
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=postgres
            - POSTGRES_DB=anovium
            - POSTGRES_HOST=postgres
            - POSTGRES_HOSTNAME=localhost
        ports:
            - '6500:5432'
        restart: always
        env_file:
            - ./backend/.env
        volumes:
            - postgres-db:/var/lib/postgresql/data
    app:
        container_name: frontend
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - '127.0.0.1:3000:3000'
        expose:
            - 3000
    backend:
        container_name: backend
        env_file:
            - ./backend/.env
        restart: always
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        ports:
            - '127.0.0.1:8000:8000'
        expose:
            - 8000
volumes:
    postgres-db:
