export const CREATE_ADDPACKAGE = "CREATE_ADDPACKAGE";
export const CREATE_ADDPACKAGE_SUCCESS = "CREATE_ADDPACKAGE_SUCCESS";
export const CREATE_ADDPACKAGE_FAILURE = "CREATE_ADDPACKAGE_FAILURE";

export const GET_ADDPACKAGE = "GET_ADDPACKAGE";
export const GET_ADDPACKAGE_SUCCESS = "GET_ADDPACKAGE_SUCCESS";
export const GET_ADDPACKAGE_FAILURE = "GET_ADDPACKAGE_FAILURE";