"""'create_package'

Revision ID: 2f32a4cd31b8
Revises: 
Create Date: 2023-10-10 14:38:54.126189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f32a4cd31b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_address', sa.String(), nullable=False),
    sa.Column('destination_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_destination_address'), 'package', ['destination_address'], unique=False)
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=True)
    op.create_index(op.f('ix_package_return_address'), 'package', ['return_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_return_address'), table_name='package')
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_index(op.f('ix_package_destination_address'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
